GET {{host}}/api/blogs

###
POST {{host}}/api/blogs
Content-Type: application/json

{
  "title": "Six of Crows",
  "author": "Meqdad",
  "url": "Meqdad.com",
  "likes": 999
}

###
POST {{host}}/api/users
Content-Type: application/json

{
    "username": "ciri",
    "name": "Cirilla",
    "password": "dodo"
}

###
POST {{host}}/api/blogs
Content-Type: application/json

{
  "title": "Hearts of Stone",
  "author": "Garelt",
  "url": "dodo.com",
  "userID": "649781348c8837922c2464ed"
}

###
POST {{host}}/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcGJhdyIsImlkIjoiNjQ5NzgxMzQ4Yzg4Mzc5MjJjMjQ2NGVkIiwiaWF0IjoxNjg3NjUwOTA4fQ.D1pDdqcN8tOxht9EYUVlPbsDzzpjy3MsqHjXroB_3t4

{
  "title": "qqqq",
  "author": "qqqq",
  "url": "qqq.com",
  "userID": "649781348c8837922c2464ed"
}

###
PUT {{host}}/api/blogs/649781478c8837922c2464f3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcGJhdyIsImlkIjoiNjQ5NzgxMzQ4Yzg4Mzc5MjJjMjQ2NGVkIiwiaWF0IjoxNjg3NjUwOTA4fQ.D1pDdqcN8tOxht9EYUVlPbsDzzpjy3MsqHjXroB_3t4

{
  "likes": 100,
  "url": "Meqdad.meq"
}

###
PUT {{host}}/api/blogs/649781478c8837922c2464f3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNpcmkiLCJpZCI6IjY0OTc5Y2FmYzNjMjgyNWJlOWZiMzJmZCIsImlhdCI6MTY4NzY2MDk5Mn0.6YxNaS44BD2ElSDJjdepS80fycYdPhMK3aEMGH55M5k

{
  "likes": 100,
  "url": "Meqdad.meq"
}

###
GET {{host}}/api/blogs
Content-Type: application/json

###
GET {{host}}/api/users
Content-Type: application/json


###
POST {{host}}/api/login
Content-Type: application/json

{
  "username": "ciri",
  "password": "dodo"
}

###
DELETE {{host}}/api/blogs/6497a75bdf3ca7a06a9bce18
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcGJhdyIsImlkIjoiNjQ5NzgxMzQ4Yzg4Mzc5MjJjMjQ2NGVkIiwiaWF0IjoxNjg3NjUwOTA4fQ.D1pDdqcN8tOxht9EYUVlPbsDzzpjy3MsqHjXroB_3t4
